title: Dor Technologies
email: api@getdor.com
description: "From small business to enterprise, go beyond people counting with retail analytics from Dor."
baseurl: ""
url: "https://getdor.com"
app_url: "https://app.getdor.com"
source: src
destination: _dist
env: production
include:
  - _views
show_dir_listing: false
keep_files:
  - assets/
forms:
  portalId: "1694028"
  partners: "3edd0f11-a10a-4e5f-b994-c170485ad166"
  getdor: "8fe0d8e6-218c-4e3d-8d04-fdc5bc7613ab"
  pricing: "c83cb1dc-1afe-4e9e-a67f-f52d1f4c429e"
  press: "2d610ce2-58ab-4623-8544-927fe358a97a"
plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
  - .gitignore
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src/assets/css/
  - [css/]
