title: Dor Technologies
email: api@getdor.com
description: "From small business to enterprise, go beyond people counting with retail analytics from Dor."
baseurl: ""
url: "http://staging.getdor.com/"
source: src
destination: _dist
include:
  - _views
show_dir_listing: false
keep_files:
  - assets/
forms:
  portalId: "1694028"
  partners: "3d23e9a6-e9a5-43ae-8f9b-6ca989b929ad"
  getdor: "84aad393-73fb-4f53-83d0-67fe7d68b253"
  pricing: "779c1985-4837-4301-856c-86015ce17bf6"
  press: "e7418bfb-0790-4636-816d-c28421420503"
urls:
  app: "https://app-staging.getdor.com/dashboard"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
  - .gitignore
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src/assets/css/
  - [css/]
